### ISSUE TITLE
Can't boot from windows gpt usb windows 10 install

### ISSUE THREAD

**Issue by marcelloc** [m13253/clover-linux-installer#6]
HI,

First of all, thanks for the greak work on this. I'm trying to boot a gpt usb windows 10 install  on and asus non UEFI bios. 

I build a usb flash with you UEFI boot and can receive first "press any key to boot from cd or DVD" on windows install but it does not boot. 
if I hit enter or any key, the counter stops but install does not starts. Same behavior if I do not press any key . 
If I hit a key o enter 3 times, I get back to UEFI menu.

**Comment by 0xbaaaadf8** [comment]
I have encountered the same problem when I was trying to install Windows 10 by this method. However, I have since found a workaround that allowed me to skip this problem.

I assume you know the name of the partition on the USB drive that is to be booted from.
I also assume you've used the Windows 10 media creation tool. If you've used Rufus, which uses UEFI:NTFS (or some other tool,) please let me know. 

1. From a powered-off state, turn on your computer, and wait until you see the Clover menu.
2. Exit Clover by pressing the right arrow key several times until you highlight an option named "Exit Clover".

From this point, you should see a monochrome menu.

3. Select "Boot Maintenance Manager".
4. Select "Boot from file".
5. You'll need to select which partition to boot from. In this case, it's the partition on the USB flash drive.
6. Select "efi".
7. Select "boot".
8. Select "BOOTX64.EFI", and volia! Windows setup should start soon.

**Comment by m13253** [comment]
Sorry for the late reply! Thanks NoodleFork for giving us a solution. May I close this issue now?

**Comment by marcelloc** [comment]
Sure. Thanks for you and @NoodleFork.
