### ISSUE TITLE
Clover release location moved from SourceForge to GitHub

### ISSUE THREAD

**Issue by nnn1590** [m13253/clover-linux-installer#8]
When I downloaded https://sourceforge.net/projects/cloverefiboot/files/latest/download, there was a file called `New_version.rtf` which was written:
> You are in the wrong place, go here
https://github.com/CloverHackyColor/CloverBootloader/releases

So I think this code: https://github.com/m13253/clover-linux-installer/blob/489513812b7ec5c23a22a431e9a12c0740c8f174/install.sh#L77
 needs to be changed.

This sentence has been translated from Japanese to English by Google Translate.

<details>
<summary>Japanese | 日本語</summary>

# Cloverのリリース場所はSourceForgeからGitHubに移動しました
https://sourceforge.net/projects/cloverefiboot/files/latest/download をダウンロードすると`New_version.rtf`というファイルがあり、そこには
> You are in the wrong place, go here
https://github.com/CloverHackyColor/CloverBootloader/releases

と書かれていました。
なのでこのコード: https://github.com/m13253/clover-linux-installer/blob/489513812b7ec5c23a22a431e9a12c0740c8f174/install.sh#L77 は変更する必要があると思います。

この文章はGoogle 翻訳によって日本語から英語に翻訳されました。
</details>

**Comment by nnn1590** [comment]
Reference | 参考: https://gist.github.com/steinwaywhw/a4cd19cda655b8249d908261a62687f8

pkg files are now released directly rather than in zip.
pkgファイルはzipの中ではなく直接リリースされるようになりました。

```bash
    log curl -o Clover.zip.part -C - -L $(curl -s https://api.github.com/repos/CloverHackyColor/CloverBootloader/releases/latest | grep '/Clover.*\.pkg' | cut -d : -f 2,3 | tr -d \" | sed -e's/^ //')
```

**Comment by m13253** [comment]
メッセージありがとうございます。

いま、ソフトが動作しないのは申し訳ございません。Cloverがダウンロードアドレスの変更について、了解いたしました。

GitHub APIの結果がJSON形式であることを考慮すると、安全上の理由から、URLを取得するには、おそらく正規表現の代わりにJSON構文解析器を使用する必要があります。修正には時間がかかる場合があります。

修正するまでしばらくお待ちください。提案があった場合は、お気軽に教えてください。

---

Thank you for your message.

I’m sorry for the misbehavior of the software. And I am now aware that the download address of Clover has changed.

Considering the result of GitHub API is in JSON format, I probably want to use a JSON parser, instead of RegExp to get the download URL. It may take some time before I figure out the fix.

Please wait until I get the problem fixed. Please feel free to tell me if you have any opinions.

**Comment by m13253** [comment]
問題を修正しました。
新しいバージョンをお試しください。

---

I have fixed the problem.
Would you please try the new version?

**Comment by nnn1590** [comment]
ありがとうございます！
___
Thank you!
